### PR TITLE
feat: project governance llm checks

### PR DESCRIPTION
**Pull request by gaurpulkit**
> [!IMPORTANT]
> Adds project governance LLM checks to `APIClient`, integrates them into `project-health` CLI command, and updates `DBTInsightGenerator` to include these checks in reports.
> 
>   - **Behavior**:
>     - Adds `get_project_governance_llm_checks()` and `run_project_governance_llm_checks()` to `APIClient` in `client.py` for governance checks.
>     - Integrates LLM checks into `project_health()` in `cli.py`, displaying results in CLI.
>   - **CLI**:
>     - Adds `--token`, `--instance-name`, and `--backend-url` options to `project-health` command in `cli.py`.
>     - Displays LLM check results with detailed insights in `project-health` command.
>   - **Utils**:
>     - Adds utility functions `get_project_governance_llm_checks()` and `run_project_governance_llm_checks()` in `utils.py` for API interaction.
>   - **Constants**:
>     - Adds `LLM` constant to `constants.py` for categorizing LLM insights.
>   - **Executor**:
>     - Updates `DBTInsightGenerator` in `executor.py` to run LLM checks and include results in reports.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=AltimateAI%2Fdatapilot-cli&utm_source=github&utm_medium=referral)<sup> for a499fee798ecec698b983fffef8c75638c312961. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by suryaiyer95 — APPROVED** [review]
Looks okay, @mdesmet  Please have a look as well

**Comment by suryaiyer95** [comment]
@gaurpulkit Some tests are failing, Please have a look

**Comment by mdesmet** [comment]
@gaurpulkit : The checks are failing, can you PTAL?

**Review by mdesmet — APPROVED** [review]
LGTM except 3.8 compatiblilty

**Comment by mdesmet** [comment]
Also is following scenario property handled:

The user has a config that has LLM checks but forgets to provide the api key and tenant?

**Pull request merged**
